// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-study/go-ent-pokemon/ent/battle"
	"go-study/go-ent-pokemon/ent/pokemon"
	"go-study/go-ent-pokemon/ent/predicate"
	"sync"
	"time"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeBattle  = "Battle"
	TypePokemon = "Pokemon"
)

// BattleMutation represents an operation that mutates the Battle nodes in the graph.
type BattleMutation struct {
	config
	op               Op
	typ              string
	id               *int
	result           *string
	create_at        *time.Time
	update_at        *time.Time
	clearedFields    map[string]struct{}
	contender        *int
	clearedcontender bool
	oponent          *int
	clearedoponent   bool
	done             bool
	oldValue         func(context.Context) (*Battle, error)
	predicates       []predicate.Battle
}

var _ ent.Mutation = (*BattleMutation)(nil)

// battleOption allows management of the mutation configuration using functional options.
type battleOption func(*BattleMutation)

// newBattleMutation creates new mutation for the Battle entity.
func newBattleMutation(c config, op Op, opts ...battleOption) *BattleMutation {
	m := &BattleMutation{
		config:        c,
		op:            op,
		typ:           TypeBattle,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withBattleID sets the ID field of the mutation.
func withBattleID(id int) battleOption {
	return func(m *BattleMutation) {
		var (
			err   error
			once  sync.Once
			value *Battle
		)
		m.oldValue = func(ctx context.Context) (*Battle, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Battle.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withBattle sets the old Battle of the mutation.
func withBattle(node *Battle) battleOption {
	return func(m *BattleMutation) {
		m.oldValue = func(context.Context) (*Battle, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m BattleMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m BattleMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Battle entities.
func (m *BattleMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *BattleMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *BattleMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Battle.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetResult sets the "result" field.
func (m *BattleMutation) SetResult(s string) {
	m.result = &s
}

// Result returns the value of the "result" field in the mutation.
func (m *BattleMutation) Result() (r string, exists bool) {
	v := m.result
	if v == nil {
		return
	}
	return *v, true
}

// OldResult returns the old "result" field's value of the Battle entity.
// If the Battle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BattleMutation) OldResult(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResult is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResult requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResult: %w", err)
	}
	return oldValue.Result, nil
}

// ResetResult resets all changes to the "result" field.
func (m *BattleMutation) ResetResult() {
	m.result = nil
}

// SetCreateAt sets the "create_at" field.
func (m *BattleMutation) SetCreateAt(t time.Time) {
	m.create_at = &t
}

// CreateAt returns the value of the "create_at" field in the mutation.
func (m *BattleMutation) CreateAt() (r time.Time, exists bool) {
	v := m.create_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateAt returns the old "create_at" field's value of the Battle entity.
// If the Battle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BattleMutation) OldCreateAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateAt: %w", err)
	}
	return oldValue.CreateAt, nil
}

// ResetCreateAt resets all changes to the "create_at" field.
func (m *BattleMutation) ResetCreateAt() {
	m.create_at = nil
}

// SetUpdateAt sets the "update_at" field.
func (m *BattleMutation) SetUpdateAt(t time.Time) {
	m.update_at = &t
}

// UpdateAt returns the value of the "update_at" field in the mutation.
func (m *BattleMutation) UpdateAt() (r time.Time, exists bool) {
	v := m.update_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateAt returns the old "update_at" field's value of the Battle entity.
// If the Battle object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BattleMutation) OldUpdateAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateAt: %w", err)
	}
	return oldValue.UpdateAt, nil
}

// ResetUpdateAt resets all changes to the "update_at" field.
func (m *BattleMutation) ResetUpdateAt() {
	m.update_at = nil
}

// SetContenderID sets the "contender" edge to the Pokemon entity by id.
func (m *BattleMutation) SetContenderID(id int) {
	m.contender = &id
}

// ClearContender clears the "contender" edge to the Pokemon entity.
func (m *BattleMutation) ClearContender() {
	m.clearedcontender = true
}

// ContenderCleared reports if the "contender" edge to the Pokemon entity was cleared.
func (m *BattleMutation) ContenderCleared() bool {
	return m.clearedcontender
}

// ContenderID returns the "contender" edge ID in the mutation.
func (m *BattleMutation) ContenderID() (id int, exists bool) {
	if m.contender != nil {
		return *m.contender, true
	}
	return
}

// ContenderIDs returns the "contender" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ContenderID instead. It exists only for internal usage by the builders.
func (m *BattleMutation) ContenderIDs() (ids []int) {
	if id := m.contender; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetContender resets all changes to the "contender" edge.
func (m *BattleMutation) ResetContender() {
	m.contender = nil
	m.clearedcontender = false
}

// SetOponentID sets the "oponent" edge to the Pokemon entity by id.
func (m *BattleMutation) SetOponentID(id int) {
	m.oponent = &id
}

// ClearOponent clears the "oponent" edge to the Pokemon entity.
func (m *BattleMutation) ClearOponent() {
	m.clearedoponent = true
}

// OponentCleared reports if the "oponent" edge to the Pokemon entity was cleared.
func (m *BattleMutation) OponentCleared() bool {
	return m.clearedoponent
}

// OponentID returns the "oponent" edge ID in the mutation.
func (m *BattleMutation) OponentID() (id int, exists bool) {
	if m.oponent != nil {
		return *m.oponent, true
	}
	return
}

// OponentIDs returns the "oponent" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// OponentID instead. It exists only for internal usage by the builders.
func (m *BattleMutation) OponentIDs() (ids []int) {
	if id := m.oponent; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetOponent resets all changes to the "oponent" edge.
func (m *BattleMutation) ResetOponent() {
	m.oponent = nil
	m.clearedoponent = false
}

// Where appends a list predicates to the BattleMutation builder.
func (m *BattleMutation) Where(ps ...predicate.Battle) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *BattleMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Battle).
func (m *BattleMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *BattleMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.result != nil {
		fields = append(fields, battle.FieldResult)
	}
	if m.create_at != nil {
		fields = append(fields, battle.FieldCreateAt)
	}
	if m.update_at != nil {
		fields = append(fields, battle.FieldUpdateAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *BattleMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case battle.FieldResult:
		return m.Result()
	case battle.FieldCreateAt:
		return m.CreateAt()
	case battle.FieldUpdateAt:
		return m.UpdateAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *BattleMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case battle.FieldResult:
		return m.OldResult(ctx)
	case battle.FieldCreateAt:
		return m.OldCreateAt(ctx)
	case battle.FieldUpdateAt:
		return m.OldUpdateAt(ctx)
	}
	return nil, fmt.Errorf("unknown Battle field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BattleMutation) SetField(name string, value ent.Value) error {
	switch name {
	case battle.FieldResult:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResult(v)
		return nil
	case battle.FieldCreateAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateAt(v)
		return nil
	case battle.FieldUpdateAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateAt(v)
		return nil
	}
	return fmt.Errorf("unknown Battle field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *BattleMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *BattleMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BattleMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Battle numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *BattleMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *BattleMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *BattleMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Battle nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *BattleMutation) ResetField(name string) error {
	switch name {
	case battle.FieldResult:
		m.ResetResult()
		return nil
	case battle.FieldCreateAt:
		m.ResetCreateAt()
		return nil
	case battle.FieldUpdateAt:
		m.ResetUpdateAt()
		return nil
	}
	return fmt.Errorf("unknown Battle field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *BattleMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.contender != nil {
		edges = append(edges, battle.EdgeContender)
	}
	if m.oponent != nil {
		edges = append(edges, battle.EdgeOponent)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *BattleMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case battle.EdgeContender:
		if id := m.contender; id != nil {
			return []ent.Value{*id}
		}
	case battle.EdgeOponent:
		if id := m.oponent; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *BattleMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *BattleMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *BattleMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedcontender {
		edges = append(edges, battle.EdgeContender)
	}
	if m.clearedoponent {
		edges = append(edges, battle.EdgeOponent)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *BattleMutation) EdgeCleared(name string) bool {
	switch name {
	case battle.EdgeContender:
		return m.clearedcontender
	case battle.EdgeOponent:
		return m.clearedoponent
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *BattleMutation) ClearEdge(name string) error {
	switch name {
	case battle.EdgeContender:
		m.ClearContender()
		return nil
	case battle.EdgeOponent:
		m.ClearOponent()
		return nil
	}
	return fmt.Errorf("unknown Battle unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *BattleMutation) ResetEdge(name string) error {
	switch name {
	case battle.EdgeContender:
		m.ResetContender()
		return nil
	case battle.EdgeOponent:
		m.ResetOponent()
		return nil
	}
	return fmt.Errorf("unknown Battle edge %s", name)
}

// PokemonMutation represents an operation that mutates the Pokemon nodes in the graph.
type PokemonMutation struct {
	config
	op               Op
	typ              string
	id               *int
	name             *string
	description      *string
	weight           *float64
	addweight        *float64
	height           *float64
	addheight        *float64
	create_at        *time.Time
	update_at        *time.Time
	clearedFields    map[string]struct{}
	fights           map[int]struct{}
	removedfights    map[int]struct{}
	clearedfights    bool
	opponents        map[int]struct{}
	removedopponents map[int]struct{}
	clearedopponents bool
	done             bool
	oldValue         func(context.Context) (*Pokemon, error)
	predicates       []predicate.Pokemon
}

var _ ent.Mutation = (*PokemonMutation)(nil)

// pokemonOption allows management of the mutation configuration using functional options.
type pokemonOption func(*PokemonMutation)

// newPokemonMutation creates new mutation for the Pokemon entity.
func newPokemonMutation(c config, op Op, opts ...pokemonOption) *PokemonMutation {
	m := &PokemonMutation{
		config:        c,
		op:            op,
		typ:           TypePokemon,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPokemonID sets the ID field of the mutation.
func withPokemonID(id int) pokemonOption {
	return func(m *PokemonMutation) {
		var (
			err   error
			once  sync.Once
			value *Pokemon
		)
		m.oldValue = func(ctx context.Context) (*Pokemon, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Pokemon.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPokemon sets the old Pokemon of the mutation.
func withPokemon(node *Pokemon) pokemonOption {
	return func(m *PokemonMutation) {
		m.oldValue = func(context.Context) (*Pokemon, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PokemonMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PokemonMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Pokemon entities.
func (m *PokemonMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PokemonMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PokemonMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Pokemon.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *PokemonMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *PokemonMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Pokemon entity.
// If the Pokemon object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PokemonMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *PokemonMutation) ResetName() {
	m.name = nil
}

// SetDescription sets the "description" field.
func (m *PokemonMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *PokemonMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Pokemon entity.
// If the Pokemon object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PokemonMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *PokemonMutation) ResetDescription() {
	m.description = nil
}

// SetWeight sets the "weight" field.
func (m *PokemonMutation) SetWeight(f float64) {
	m.weight = &f
	m.addweight = nil
}

// Weight returns the value of the "weight" field in the mutation.
func (m *PokemonMutation) Weight() (r float64, exists bool) {
	v := m.weight
	if v == nil {
		return
	}
	return *v, true
}

// OldWeight returns the old "weight" field's value of the Pokemon entity.
// If the Pokemon object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PokemonMutation) OldWeight(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldWeight is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldWeight requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldWeight: %w", err)
	}
	return oldValue.Weight, nil
}

// AddWeight adds f to the "weight" field.
func (m *PokemonMutation) AddWeight(f float64) {
	if m.addweight != nil {
		*m.addweight += f
	} else {
		m.addweight = &f
	}
}

// AddedWeight returns the value that was added to the "weight" field in this mutation.
func (m *PokemonMutation) AddedWeight() (r float64, exists bool) {
	v := m.addweight
	if v == nil {
		return
	}
	return *v, true
}

// ResetWeight resets all changes to the "weight" field.
func (m *PokemonMutation) ResetWeight() {
	m.weight = nil
	m.addweight = nil
}

// SetHeight sets the "height" field.
func (m *PokemonMutation) SetHeight(f float64) {
	m.height = &f
	m.addheight = nil
}

// Height returns the value of the "height" field in the mutation.
func (m *PokemonMutation) Height() (r float64, exists bool) {
	v := m.height
	if v == nil {
		return
	}
	return *v, true
}

// OldHeight returns the old "height" field's value of the Pokemon entity.
// If the Pokemon object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PokemonMutation) OldHeight(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHeight is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHeight requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHeight: %w", err)
	}
	return oldValue.Height, nil
}

// AddHeight adds f to the "height" field.
func (m *PokemonMutation) AddHeight(f float64) {
	if m.addheight != nil {
		*m.addheight += f
	} else {
		m.addheight = &f
	}
}

// AddedHeight returns the value that was added to the "height" field in this mutation.
func (m *PokemonMutation) AddedHeight() (r float64, exists bool) {
	v := m.addheight
	if v == nil {
		return
	}
	return *v, true
}

// ResetHeight resets all changes to the "height" field.
func (m *PokemonMutation) ResetHeight() {
	m.height = nil
	m.addheight = nil
}

// SetCreateAt sets the "create_at" field.
func (m *PokemonMutation) SetCreateAt(t time.Time) {
	m.create_at = &t
}

// CreateAt returns the value of the "create_at" field in the mutation.
func (m *PokemonMutation) CreateAt() (r time.Time, exists bool) {
	v := m.create_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreateAt returns the old "create_at" field's value of the Pokemon entity.
// If the Pokemon object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PokemonMutation) OldCreateAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreateAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreateAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreateAt: %w", err)
	}
	return oldValue.CreateAt, nil
}

// ResetCreateAt resets all changes to the "create_at" field.
func (m *PokemonMutation) ResetCreateAt() {
	m.create_at = nil
}

// SetUpdateAt sets the "update_at" field.
func (m *PokemonMutation) SetUpdateAt(t time.Time) {
	m.update_at = &t
}

// UpdateAt returns the value of the "update_at" field in the mutation.
func (m *PokemonMutation) UpdateAt() (r time.Time, exists bool) {
	v := m.update_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdateAt returns the old "update_at" field's value of the Pokemon entity.
// If the Pokemon object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PokemonMutation) OldUpdateAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdateAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdateAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdateAt: %w", err)
	}
	return oldValue.UpdateAt, nil
}

// ResetUpdateAt resets all changes to the "update_at" field.
func (m *PokemonMutation) ResetUpdateAt() {
	m.update_at = nil
}

// AddFightIDs adds the "fights" edge to the Battle entity by ids.
func (m *PokemonMutation) AddFightIDs(ids ...int) {
	if m.fights == nil {
		m.fights = make(map[int]struct{})
	}
	for i := range ids {
		m.fights[ids[i]] = struct{}{}
	}
}

// ClearFights clears the "fights" edge to the Battle entity.
func (m *PokemonMutation) ClearFights() {
	m.clearedfights = true
}

// FightsCleared reports if the "fights" edge to the Battle entity was cleared.
func (m *PokemonMutation) FightsCleared() bool {
	return m.clearedfights
}

// RemoveFightIDs removes the "fights" edge to the Battle entity by IDs.
func (m *PokemonMutation) RemoveFightIDs(ids ...int) {
	if m.removedfights == nil {
		m.removedfights = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.fights, ids[i])
		m.removedfights[ids[i]] = struct{}{}
	}
}

// RemovedFights returns the removed IDs of the "fights" edge to the Battle entity.
func (m *PokemonMutation) RemovedFightsIDs() (ids []int) {
	for id := range m.removedfights {
		ids = append(ids, id)
	}
	return
}

// FightsIDs returns the "fights" edge IDs in the mutation.
func (m *PokemonMutation) FightsIDs() (ids []int) {
	for id := range m.fights {
		ids = append(ids, id)
	}
	return
}

// ResetFights resets all changes to the "fights" edge.
func (m *PokemonMutation) ResetFights() {
	m.fights = nil
	m.clearedfights = false
	m.removedfights = nil
}

// AddOpponentIDs adds the "opponents" edge to the Battle entity by ids.
func (m *PokemonMutation) AddOpponentIDs(ids ...int) {
	if m.opponents == nil {
		m.opponents = make(map[int]struct{})
	}
	for i := range ids {
		m.opponents[ids[i]] = struct{}{}
	}
}

// ClearOpponents clears the "opponents" edge to the Battle entity.
func (m *PokemonMutation) ClearOpponents() {
	m.clearedopponents = true
}

// OpponentsCleared reports if the "opponents" edge to the Battle entity was cleared.
func (m *PokemonMutation) OpponentsCleared() bool {
	return m.clearedopponents
}

// RemoveOpponentIDs removes the "opponents" edge to the Battle entity by IDs.
func (m *PokemonMutation) RemoveOpponentIDs(ids ...int) {
	if m.removedopponents == nil {
		m.removedopponents = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.opponents, ids[i])
		m.removedopponents[ids[i]] = struct{}{}
	}
}

// RemovedOpponents returns the removed IDs of the "opponents" edge to the Battle entity.
func (m *PokemonMutation) RemovedOpponentsIDs() (ids []int) {
	for id := range m.removedopponents {
		ids = append(ids, id)
	}
	return
}

// OpponentsIDs returns the "opponents" edge IDs in the mutation.
func (m *PokemonMutation) OpponentsIDs() (ids []int) {
	for id := range m.opponents {
		ids = append(ids, id)
	}
	return
}

// ResetOpponents resets all changes to the "opponents" edge.
func (m *PokemonMutation) ResetOpponents() {
	m.opponents = nil
	m.clearedopponents = false
	m.removedopponents = nil
}

// Where appends a list predicates to the PokemonMutation builder.
func (m *PokemonMutation) Where(ps ...predicate.Pokemon) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *PokemonMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Pokemon).
func (m *PokemonMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PokemonMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.name != nil {
		fields = append(fields, pokemon.FieldName)
	}
	if m.description != nil {
		fields = append(fields, pokemon.FieldDescription)
	}
	if m.weight != nil {
		fields = append(fields, pokemon.FieldWeight)
	}
	if m.height != nil {
		fields = append(fields, pokemon.FieldHeight)
	}
	if m.create_at != nil {
		fields = append(fields, pokemon.FieldCreateAt)
	}
	if m.update_at != nil {
		fields = append(fields, pokemon.FieldUpdateAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PokemonMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pokemon.FieldName:
		return m.Name()
	case pokemon.FieldDescription:
		return m.Description()
	case pokemon.FieldWeight:
		return m.Weight()
	case pokemon.FieldHeight:
		return m.Height()
	case pokemon.FieldCreateAt:
		return m.CreateAt()
	case pokemon.FieldUpdateAt:
		return m.UpdateAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PokemonMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pokemon.FieldName:
		return m.OldName(ctx)
	case pokemon.FieldDescription:
		return m.OldDescription(ctx)
	case pokemon.FieldWeight:
		return m.OldWeight(ctx)
	case pokemon.FieldHeight:
		return m.OldHeight(ctx)
	case pokemon.FieldCreateAt:
		return m.OldCreateAt(ctx)
	case pokemon.FieldUpdateAt:
		return m.OldUpdateAt(ctx)
	}
	return nil, fmt.Errorf("unknown Pokemon field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PokemonMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pokemon.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case pokemon.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case pokemon.FieldWeight:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetWeight(v)
		return nil
	case pokemon.FieldHeight:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHeight(v)
		return nil
	case pokemon.FieldCreateAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreateAt(v)
		return nil
	case pokemon.FieldUpdateAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdateAt(v)
		return nil
	}
	return fmt.Errorf("unknown Pokemon field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PokemonMutation) AddedFields() []string {
	var fields []string
	if m.addweight != nil {
		fields = append(fields, pokemon.FieldWeight)
	}
	if m.addheight != nil {
		fields = append(fields, pokemon.FieldHeight)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PokemonMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case pokemon.FieldWeight:
		return m.AddedWeight()
	case pokemon.FieldHeight:
		return m.AddedHeight()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PokemonMutation) AddField(name string, value ent.Value) error {
	switch name {
	case pokemon.FieldWeight:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddWeight(v)
		return nil
	case pokemon.FieldHeight:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddHeight(v)
		return nil
	}
	return fmt.Errorf("unknown Pokemon numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PokemonMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PokemonMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PokemonMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Pokemon nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PokemonMutation) ResetField(name string) error {
	switch name {
	case pokemon.FieldName:
		m.ResetName()
		return nil
	case pokemon.FieldDescription:
		m.ResetDescription()
		return nil
	case pokemon.FieldWeight:
		m.ResetWeight()
		return nil
	case pokemon.FieldHeight:
		m.ResetHeight()
		return nil
	case pokemon.FieldCreateAt:
		m.ResetCreateAt()
		return nil
	case pokemon.FieldUpdateAt:
		m.ResetUpdateAt()
		return nil
	}
	return fmt.Errorf("unknown Pokemon field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PokemonMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.fights != nil {
		edges = append(edges, pokemon.EdgeFights)
	}
	if m.opponents != nil {
		edges = append(edges, pokemon.EdgeOpponents)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PokemonMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case pokemon.EdgeFights:
		ids := make([]ent.Value, 0, len(m.fights))
		for id := range m.fights {
			ids = append(ids, id)
		}
		return ids
	case pokemon.EdgeOpponents:
		ids := make([]ent.Value, 0, len(m.opponents))
		for id := range m.opponents {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PokemonMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedfights != nil {
		edges = append(edges, pokemon.EdgeFights)
	}
	if m.removedopponents != nil {
		edges = append(edges, pokemon.EdgeOpponents)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PokemonMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case pokemon.EdgeFights:
		ids := make([]ent.Value, 0, len(m.removedfights))
		for id := range m.removedfights {
			ids = append(ids, id)
		}
		return ids
	case pokemon.EdgeOpponents:
		ids := make([]ent.Value, 0, len(m.removedopponents))
		for id := range m.removedopponents {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PokemonMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedfights {
		edges = append(edges, pokemon.EdgeFights)
	}
	if m.clearedopponents {
		edges = append(edges, pokemon.EdgeOpponents)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PokemonMutation) EdgeCleared(name string) bool {
	switch name {
	case pokemon.EdgeFights:
		return m.clearedfights
	case pokemon.EdgeOpponents:
		return m.clearedopponents
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PokemonMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Pokemon unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PokemonMutation) ResetEdge(name string) error {
	switch name {
	case pokemon.EdgeFights:
		m.ResetFights()
		return nil
	case pokemon.EdgeOpponents:
		m.ResetOpponents()
		return nil
	}
	return fmt.Errorf("unknown Pokemon edge %s", name)
}
