// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-study/go-ent-pokemon/ent/battle"
	"go-study/go-ent-pokemon/ent/pokemon"
	"go-study/go-ent-pokemon/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	battleFields := schema.Battle{}.Fields()
	_ = battleFields
	// battleDescCreateAt is the schema descriptor for create_at field.
	battleDescCreateAt := battleFields[2].Descriptor()
	// battle.DefaultCreateAt holds the default value on creation for the create_at field.
	battle.DefaultCreateAt = battleDescCreateAt.Default.(func() time.Time)
	// battleDescUpdateAt is the schema descriptor for update_at field.
	battleDescUpdateAt := battleFields[3].Descriptor()
	// battle.DefaultUpdateAt holds the default value on creation for the update_at field.
	battle.DefaultUpdateAt = battleDescUpdateAt.Default.(func() time.Time)
	pokemonFields := schema.Pokemon{}.Fields()
	_ = pokemonFields
	// pokemonDescName is the schema descriptor for name field.
	pokemonDescName := pokemonFields[1].Descriptor()
	// pokemon.NameValidator is a validator for the "name" field. It is called by the builders before save.
	pokemon.NameValidator = pokemonDescName.Validators[0].(func(string) error)
	// pokemonDescDescription is the schema descriptor for description field.
	pokemonDescDescription := pokemonFields[2].Descriptor()
	// pokemon.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	pokemon.DescriptionValidator = pokemonDescDescription.Validators[0].(func(string) error)
	// pokemonDescCreateAt is the schema descriptor for create_at field.
	pokemonDescCreateAt := pokemonFields[5].Descriptor()
	// pokemon.DefaultCreateAt holds the default value on creation for the create_at field.
	pokemon.DefaultCreateAt = pokemonDescCreateAt.Default.(func() time.Time)
	// pokemonDescUpdateAt is the schema descriptor for update_at field.
	pokemonDescUpdateAt := pokemonFields[6].Descriptor()
	// pokemon.DefaultUpdateAt holds the default value on creation for the update_at field.
	pokemon.DefaultUpdateAt = pokemonDescUpdateAt.Default.(func() time.Time)
}
