// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/cap.proto

package cap

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Cap service

func NewCapEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Cap service

type CapService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Cap_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Cap_PingPongService, error)
}

type capService struct {
	c    client.Client
	name string
}

func NewCapService(name string, c client.Client) CapService {
	return &capService{
		c:    c,
		name: name,
	}
}

func (c *capService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Cap.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Cap_StreamService, error) {
	req := c.c.NewRequest(c.name, "Cap.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &capServiceStream{stream}, nil
}

type Cap_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type capServiceStream struct {
	stream client.Stream
}

func (x *capServiceStream) Close() error {
	return x.stream.Close()
}

func (x *capServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *capServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *capServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *capServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *capService) PingPong(ctx context.Context, opts ...client.CallOption) (Cap_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Cap.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &capServicePingPong{stream}, nil
}

type Cap_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type capServicePingPong struct {
	stream client.Stream
}

func (x *capServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *capServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *capServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *capServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *capServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *capServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Cap service

type CapHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Cap_StreamStream) error
	PingPong(context.Context, Cap_PingPongStream) error
}

func RegisterCapHandler(s server.Server, hdlr CapHandler, opts ...server.HandlerOption) error {
	type cap interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Cap struct {
		cap
	}
	h := &capHandler{hdlr}
	return s.Handle(s.NewHandler(&Cap{h}, opts...))
}

type capHandler struct {
	CapHandler
}

func (h *capHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.CapHandler.Call(ctx, in, out)
}

func (h *capHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.CapHandler.Stream(ctx, m, &capStreamStream{stream})
}

type Cap_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type capStreamStream struct {
	stream server.Stream
}

func (x *capStreamStream) Close() error {
	return x.stream.Close()
}

func (x *capStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *capStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *capStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *capStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *capHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.CapHandler.PingPong(ctx, &capPingPongStream{stream})
}

type Cap_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type capPingPongStream struct {
	stream server.Stream
}

func (x *capPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *capPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *capPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *capPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *capPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *capPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
