// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitRoot(name string) Root {
	leaf := NewLeaf(name)
	branch := NewBranch(leaf)
	root := NewRoot(branch)
	return root
}

func InitRootWithSet(name string) Root {
	leaf := NewLeaf(name)
	branch := NewBranch(leaf)
	root := NewRoot(branch)
	return root
}

func InitBar(foo Foo) *Bar {
	bar := NewBar(foo)
	return bar
}

// wire.go:

var NewBranchSet = wire.NewSet(NewLeaf, NewBranch)

var bind = wire.Bind(new(Fooer), new(Foo))
